<?php
require_once './router/Route.php';
$route = new Route();
$route->add('dangnhap','dangnhap.php');
$route->add('dangxuat','dangxuat.php');
$route->add('dangky','dangky.php');
$route->add('giohang','giohang.php');
$route->add('yeuthich','yeuthich.php');
$route->add('sanpham','sanpham.php');
$route->add('chitietsp','chitietsp.php');
$route->add('tintuc','tintuc.php');
$route->add('tintuc1','tintuc1.php');
$route->add('tintuc2','tintuc2.php');
$route->add('tintuc3','tintuc3.php');
$route->add('sukien1','sukien1.php');
$route->add('sukien2','sukien2.php');
$route->add('kinhdoanh1','kinhdoanh1.php');
$route->add('kinhdoanh2','kinhdoanh2.php');
$route->add('thongtintaikhoan','thongtintaikhoan.php');
$route->add('donhang','donhang.php');
$route->add('sodiachi','sodiachi.php');
$route->add('trangchu','trangchu.php');
$route->add('lienhe','lienhe.php');
$route->add('gioithieu','gioithieu.php');